image: python:3

before_script:
 - pip install doxec numpy
 - python3 setup.py install

stages:
  - test
  - benchmark

unittest:
  stage: test
  script:
    - python3 setup.py test 

README:
  stage: test
  script:
   - doxec README.md 

benchmark:
  stage: benchmark
  tags:
   - high-mem
  only:
    - master
  script:
   - pip install matplotlib
   - python3 benchmark.py

  artifacts:
    expire_in: 6 mos
    paths:
     - "bm_*.png"
    

benchmark_quick:
  stage: benchmark
  tags:
   - high-mem
  script:
   - pip install matplotlib
   - python3 benchmark.py --quick
  except:
    - master
  artifacts:
    expire_in: 1 week
    paths:
     - "bm_*.png"
    
