image: python:3

before_script:
 - pip install .
 - pip install doxec 

stages:
  - test
  - lint
  - postprocressing
  - deploy
  - benchmark

################################################################################
# Tests
pythontest:
  stage: test
  script:
    - make python-based-test

README:
  stage: test
  script:
   - doxec README.md 

cxxtest:
  stage: test
  script:
    - make install-gtest
    - make cxx-based-test

alternative_install:
    stage: test
    before_script: []
    script:
     - pip install numpy
     - python3 setup.py install
     - python3 -c 'import sortednp'
    

################################################################################
# Lint

cpplint:
  stage: lint
  script:
    - make cxx-lint

pylint:
  stage: lint
  script:
    - pip install pylint matplotlib numpy
    - make python-lint

################################################################################
# Benchmark
benchmark:
  stage: benchmark
  tags:
   - high-mem
  only:
    - master
  script:
   - pip install matplotlib
   - make benchmark -j2

  artifacts:
    expire_in: 6 mos
    paths:
     - "bm_*.png"

benchmark_quick:
  stage: benchmark
  when: manual
  tags:
   - high-mem
  script:
   - pip install matplotlib
   - QUICK='--quick' make benchmark -j2
  except:
    - master
  artifacts:
    expire_in: 1 week
    paths:
     - "bm_*.png"
    

################################################################################
# Post-procressing

readme:
  stage: postprocressing
  before_script:
    - apt-get update
    - apt-get install -y pandoc
  script:
    - pandoc -f markdown -t rst -o README.rst README.md

  artifacts:
    expire_in: 1 week
    paths:
     - "README.rst"

################################################################################
# Deploy
sdist:
  stage: deploy
  before_script: []
  dependencies:
    - readme
  script:
    - pandoc -f markdown -t rst -o README.rst README.md
    - python3 setup.py sdist
    - mv dist/* .

  artifacts:
    expire_in: 1 week
    paths:
     - "sortednp-*.tar.gz"

bdist_64bit:
  image: quay.io/pypa/manylinux1_x86_64
  stage: deploy
  before_script: []
  dependencies:
    - readme
  script:
    - pandoc -f markdown -t rst -o README.rst README.md
    - /opt/python/cp34-cp34m/bin/pip install -r requirements.txt
    - /opt/python/cp35-cp35m/bin/pip install -r requirements.txt
    - /opt/python/cp36-cp36m/bin/pip install -r requirements.txt
    - /opt/python/cp34-cp34m/bin/pip wheel .
    - /opt/python/cp35-cp35m/bin/pip wheel .
    - /opt/python/cp36-cp36m/bin/pip wheel .

  artifacts:
    expire_in: 1 week
    paths:
     - "sortednp-*.whl"

bdist_32bit:
  image: quay.io/pypa/manylinux1_i686
  stage: deploy
  before_script: []
  dependencies:
    - readme
  script:
    - pandoc -f markdown -t rst -o README.rst README.md
    - /opt/python/cp34-cp34m/bin/pip install -r requirements.txt
    - /opt/python/cp35-cp35m/bin/pip install -r requirements.txt
    - /opt/python/cp36-cp36m/bin/pip install -r requirements.txt
    - /opt/python/cp34-cp34m/bin/pip wheel .
    - /opt/python/cp35-cp35m/bin/pip wheel .
    - /opt/python/cp36-cp36m/bin/pip wheel .

  artifacts:
    expire_in: 1 week
    paths:
     - "sortednp-*.whl"


