image: python:3

before_script:
 - pip install doxec numpy
 - python3 setup.py install

stages:
  - test
  - benchmark

unittest:
  stage: test
  script:
    - python3 setup.py test 

README:
  stage: test
  script:
   - doxec README.md 

benchmark:
  stage: benchmark
  script:
   - pip install matplotlib
   - python3 benchmark.py

  artifacts:
    expire_in: 10 weeks
    paths:
     - bm_intersect.png
     - bm_merge.png
    
