image: python:3

before_script:
 - pip install .
 - pip install doxec 

stages:
  - test
  - lint
  - final

################################################################################
# Tests
pythontest:
  stage: test
  script:
    - make python-based-test

README:
  stage: test
  script:
   - doxec README.md 

cxxtest:
  stage: test
  script:
    - make install-gtest
    - make cxx-based-test

alternative_install:
    stage: test
    before_script: []
    script:
     - pip install numpy
     - python3 setup.py install
     - python3 -c 'import sortednp'
    

################################################################################
# Lint

cpplint:
  stage: lint
  script:
    - make cxx-lint

pylint:
  stage: lint
  script:
    - pip install pylint matplotlib numpy
    - make python-lint

################################################################################
# Benchmark
benchmark:
  stage: final
  tags:
   - high-mem
  only:
    - master
  script:
   - pip install matplotlib
   - make benchmark -j2

  artifacts:
    expire_in: 6 mos
    paths:
     - "bm_*.png"

benchmark_quick:
  stage: final
  tags:
   - high-mem
  script:
   - pip install matplotlib
   - QUICK='--quick' make benchmark -j2
  except:
    - master
  artifacts:
    expire_in: 1 week
    paths:
     - "bm_*.png"
    

################################################################################
# Deploy
pypi_deploy:
  stage: final
  before_script:
    - pip install twine numpy
    - apt-get update
    - apt-get install -y pandoc gnupg2
  script:
    - pandoc -f markdown -t rst -o README.rst README.md
    - python3 setup.py sdist

  artifacts:
    expire_in: 1 day
    paths:
     - "dist/*"
