image: python:3

before_script:
 - pip install doxec numpy
 - python3 setup.py install

stages:
  - test

unittest:
    stage: test
    script:
      - python3 setup.py test 

README:
    stage: test
    script:
     - doxec README.md 

